create table if not exists public.follower_snapshots (
    id bigint generated by default as identity primary key,
    platform text not null,
    followers integer not null check (followers >= 0),
    provider text not null,
    snapshot_date date not null,
    observed_at timestamptz not null,
    refreshed_at timestamptz not null,
    constraint uq_follower_platform_date unique (platform, snapshot_date)
);

create index if not exists ix_follower_snapshots_snapshot_date
    on public.follower_snapshots (snapshot_date);

alter table public.follower_snapshots enable row level security;

revoke all on table public.follower_snapshots from anon, authenticated;
revoke all on sequence public.follower_snapshots_id_seq from anon, authenticated;
